language: node_js
node_js:
  - "12"
  - "10"
before_install:
  # Create a master branch commitlint
  - git remote set-branches origin master && git fetch
deploy:
  on:
    tags: true
    branch: master
  provider: npm
  email: open-source-ops@aexp.com
  api_key:
    secure: Ej19mrN5EjAHNBdXZFcLXIxs0otYuk9qSnpTgDmeCIZWvWMGtLYBHm3akzqrGbyEXTL/ThXKODQ2N88erfb8ToMXNNh9RZFmZfS4yCHnfkfwlGRc0VD4VhfAtKhMpLh1ezF8y8BO8iPCzEa+C+Z6wW4SxIDxP98hRW0FA3DjW2LeAcmnh8hGgXOcZfvAE1zVriUIen+ORkYcL2ez93FaLZAoV8pwzzI0iG5gh5ECaawxRxLivxEolZmQLjVpUWh6O+GIUmtobMZl2eAqe1jp1mMpEcPHXzN2JynP0hivXW6VitLW43tNwzVJxqh6Mw3XEJ7Vy3lR2grl0Yjfrm+lApaY5pgN3pERly28chkg4+54iEfYVRdkE0iyHRFhphLqR+H1UXUJqtCLJN8ghtdONAH5w9DY1k9SzfXy3tyHsr7vBOIw5ZAfU9ymAERs3JEYpBdheNO08aHfTBiriCUnTQ22IWFL4JBx2n0YVynDzpTq6LRQkpYOvskDwS4Eno2k2RmX6VeSzj4bY2/pwSTyJAapL39mGner6zY12slBp5+lR/GNWwhSTaps2iGD0EYeu3fO4PkWAAFlaGGGFKEzV0tzTIQcSO69wq8DTiUQaOYijyDxIlpxXCsSlnUC5CBDZhlOWjayInzieWa5e1RuxDcCIny5KKRVzgg1xijyczA=
